trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

stages:
  - stage: Build
    jobs:
      - template: pipeline-templates/job/code-build.yml
      - template: pipeline-templates/job/dacpac-build.yml

  - stage: NugetPublish
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    jobs:
      - template: pipeline-templates/job/nuget-publish.yml


