jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration
  variables:
  - group: Prod Management Resources
  - name: buildConfiguration
    value: release
  workspace:
    clean: all
  steps:
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: 5.6.4
      useConfigFile: true
      configFilePath: GitVersion.yml

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      packagesToPack: src/SFA.DAS.Apprentice.LoginService.Messages/SFA.DAS.Apprentice.LoginService.Messages.csproj
      versioningScheme: byBuildNumber
      packDirectory: $(build.artifactstagingdirectory)/NugetPackages

  - task: DotNetCoreCLI@2
    displayName: Publish Website
    inputs:
      command: publish
      publishWebProjects: true
      projects: src/SFA.DAS.LoginService.Web/SFA.DAS.LoginService.Web.csproj
      arguments: --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: DotNetCoreCLI@2
    displayName: Publish Function
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Apprentice.LoginService.MessageHandler/SFA.DAS.Apprentice.LoginService.MessageHandler.csproj
      arguments: --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: CopyFiles@2
    displayName: Copy Files to - $(build.artifactstagingdirectory)
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact - CodeBuild
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)/publish

  - publish: $(build.artifactstagingdirectory)/NugetPackages
    artifact: NugetPackages