pool:
  name: DAS - Continuous Deployment
workspace:
  clean: all
jobs:
- deployment: NugetPush
  environment: Nuget
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: NugetPackages
        - task: NuGetCommand@2
          displayName: NuGet push
          inputs:
            command: push
            packagesToPush: $(Pipeline.Workspace)/NugetPackages/*.nupkg;!$(Pipeline.Workspace)/NugetPackages/*.symbols.nupkg
            nuGetFeedType: external
            publishFeedCredentials: SFA NuGet